version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: laravel_app:latest
    container_name: laravel_app
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html:cached
      - ./php.ini:/usr/local/etc/php/conf.d/custom.ini
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:1.25
    container_name: laravel_web
    ports:
      - "80:80"
    volumes:
      - ./:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      TZ: "Asia/Tokyo"
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel_node
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html:cached
      - /var/www/html/src/node_modules
    ports:
      - "5173:5173" # vite dev server
    command: sh -c "npm install && npm run dev"
    networks:
      - laravel

volumes:
  dbdata:

networks:
  laravel:
    driver: bridge
